### ISSUE TITLE
关于小程序文件上传问题的请教

### ISSUE THREAD

**Issue by sky508** [zlyboy/wx-formdata#1]
![image](https://user-images.githubusercontent.com/26371416/112428823-b8bd4080-8d76-11eb-8b71-4a0f4d1593a3.png)
qin请问这个filepath怎么获取

**Comment by zlyboy** [comment]
一般通过wx.chooseMessageFile(Object object)让用户选择要上传的文件，然后在回调中拿到。
小程序官方文档：[https://developers.weixin.qq.com/miniprogram/dev/api/media/image/wx.chooseMessageFile.html](url)

**Comment by sky508** [comment]
> 一般通过wx.chooseMessageFile(Object object)让用户选择要上传的文件，然后在回调中拿到。
> 小程序官方文档：[https://developers.weixin.qq.com/miniprogram/dev/api/media/image/wx.chooseMessageFile.html](url)

![image](https://user-images.githubusercontent.com/26371416/112569668-93d0d800-8e1f-11eb-91c7-6a44712f983c.png)
那你这里面的name是上传时候的文件名？还是后台接收的时候的参数名？另外你这个path是通过chooseMessageFile拿到的path，对吧？

**Comment by zlyboy** [comment]
name是后台接收的参数名，path就是chooseMessageFile拿到的path，或者其他的FileSystemManager能读取到的文件路径也可以。
[https://developers.weixin.qq.com/miniprogram/dev/framework/ability/file-system.html](url)

**Comment by sky508** [comment]
> name是后台接收的参数名，path就是chooseMessageFile拿到的path，或者其他的FileSystemManager能读取到的文件路径也可以。
> [https://developers.weixin.qq.com/miniprogram/dev/framework/ability/file-system.html](url)
![image](https://user-images.githubusercontent.com/26371416/112572906-2eccb080-8e26-11eb-8afd-3431f3955c76.png)

但是我这么用后台接收是个空的，     我这是从电脑使用微信开发者工具弹出文件选择框，然后选中文件进行上传，你方便给个你那边的测试样例瞅瞅吗？

**Comment by zlyboy** [comment]
试了一下，用开发工具添加失败，真机调试可以添加。
我改了一下，你可以拉取最新的代码再试试。

**Comment by wangfpp** [comment]
不知道为啥 提交的formData一直是空啊
```js
  let formData = new FormData();
    formData.append('file', file.path)
    // 对原始数据进行数据格式调整
    console.log(formData)
    let data = formData.getData();
      wx.request({
        url: 'http://xxx/api/file_mgr/upload',
        data: data.buffer,
        header: {
          'content-type': data.contentType
        },
        method: 'POST'
      })
```

**Comment by zlyboy** [comment]
``` javascript 
let formData = new FormData();

console.log(formData);

formData.append("name", "value");

formData.appendFile("file", tempFilePaths[0].path);

let data = formData.getData();

console.log(data);
```
为空是啥意思，输出出来大概是这样的
![1](https://user-images.githubusercontent.com/18344328/114397225-063c0900-9bd1-11eb-8b0d-43f6190b8d9b.png)

**Comment by DarkNin** [comment]
![image](https://user-images.githubusercontent.com/5499352/114403867-be6cb000-9bd7-11eb-9f31-7966c2efcee7.png)

上面说的应该是真机调试看不到请求体有form data块，我这也是，开发工具里倒是能看到

**Comment by DarkNin** [comment]
> ![image](https://user-images.githubusercontent.com/5499352/114403867-be6cb000-9bd7-11eb-9f31-7966c2efcee7.png)
> 
> 上面说的应该是真机调试看不到请求体有form data块，我这也是，开发工具里倒是能看到

![image](https://user-images.githubusercontent.com/5499352/114418873-83717900-9be5-11eb-8ce3-f4eb3f29ea47.png)
整了个demo看了下数据，普通字段拿得到，文件拿不到……

**Comment by wangfpp** [comment]
@zlyboy 同样的接口再Postman和网页中可以
小程序中不行 实在找不到问题了  后台接收不到file

**Comment by zlyboy** [comment]
好像，真机调试是不行了。。。我研究下。。。

**Comment by zlyboy** [comment]
改了一下，大概能用了。。。

**Comment by zlyboy** [comment]
> @zlyboy 同样的接口再Postman和网页中可以
> 小程序中不行 实在找不到问题了 后台接收不到file

改了一下，大概能用了。。。
