### ISSUE TITLE
传入的文本参数中，只要包含emoji表情，则会在其后附加�符号

### ISSUE THREAD

**Issue by NavinChen** [zlyboy/wx-formdata#3]

**Comment by zlyboy** [comment]
没理解啥问题？这个工具只是把传入的字符串参数转成utf8编码的bytes数组，传入啥字符串，最后提交给后台也是啥字符串。解析和显示是外部代码的事情，跟这个工具应该没有关系。

**Comment by NavinChen** [comment]
比如微信小程序传入😀表情，后端接收原样打印出来却是“😀�”

**Comment by zlyboy** [comment]
问题已修复，拉取最新代码试试

**Comment by NavinChen** [comment]
谢谢大佬

**Comment by NavinChen** [comment]
现在文本、emoji，和文件一起上传，会出现部分内容乱码

**Comment by NavinChen** [comment]
如果没有文件则不会出现这个问题

**Comment by NavinChen** [comment]
![image](https://user-images.githubusercontent.com/11780577/135249131-d3e07f97-986e-42af-8481-85650ef58501.png)

**Comment by zlyboy** [comment]
我这边也是这样，但是后台接到的数据是对的，你看下后台接到的数据是不是乱码。

**Comment by NavinChen** [comment]
后端接收到的数据确认没有问题，谢谢作者大佬
