### ISSUE TITLE
上传文件只传了一部分

### ISSUE THREAD

**Issue by chenjia111** [zlyboy/wx-formdata#5]
你好，在微信小程序使用这个npm包的时候遇到一个问题，上传文件只传了前面一部分

  wx.chooseMessageFile({
    count: 1,
    type: "file",
    extension: ["txt"],
    success(res) {
      const tempFilePaths = res.tempFiles;
      let filePath = tempFilePaths[0].path;
      let formData = new FormData();
      formData.appendFile("filename", filePath, "parameter.txt");
      let data = formData.getData();
      wx.request({
        url: "http://10.168.1.220",
        header: { "content-type": data.contentType },
        method: "POST",
        data: data.buffer,
      });
    },
  });

**Comment by zlyboy** [comment]
我用你的代码本地测试是正常的，你的文件是啥样的，后台接收又是啥样的，能提供不。

**Comment by chenjia111** [comment]
不好意思，后来调试了是接口问题，发送的请求数据没问题
