### ISSUE TITLE
调用appendFile方法文件名会变成一串ID，建议用wx.chooseMessageFile返回的原始文件名

### ISSUE THREAD

**Issue by chenjia111** [zlyboy/wx-formdata#6]
/*****外部调用*****/

  wx.chooseMessageFile({
    count: 1,
    type: "file",
    extension: ["txt"],
    success(res) {
      let filePath = res.tempFiles[0];
      let formData = new FormData();
      formData.appendFile("filename", filePath);
      let data = formData.getData();
      console.log(
        data,
        String.fromCharCode.apply(null, new Uint8Array(data.buffer))
      );
  }
})

/****formData.js***/
  this.appendFile = (name, fileObj) => {
    let buffer = fileManager.readFileSync(fileObj.path);
    if(Object.prototype.toString.call(buffer).indexOf("ArrayBuffer") < 0){
      return false;
    }
    files.push({
      name: name,
      buffer: buffer,
      fileName:fileObj.name// getFileNameFromPath(path)
    });
    return true;
  }

**Comment by zlyboy** [comment]
已添加功能：formData.appendFile("file", filepath, "文件名");
