### ISSUE TITLE
作者你好，我改了一版ts的放gitee上了，如有问题请联系我

### ISSUE THREAD

**Issue by lb091188** [zlyboy/wx-formdata#7]
[ts版本](https://gitee.com/noahliu0911/wx-formdata-ts)

**Comment by dm3030110q** [comment]
你好，我使用	formData.append("outsideSite", _this.addressName); 时发现_this.addressName如果是中文的话，发送出去的请求会是乱码，请问有解决方法吗？

**Comment by zlyboy** [comment]
好的
